// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExternalRealtimeHandoffSource } from "../ExternalRealtimeHandoffSource";
import type { RealtimeTranscriptEntry } from "../RealtimeTranscriptEntry";

/**
 * EXPERIMENTAL - structured delegation from native voice to an external backing agent.
 */
export type ThreadRealtimeExternalHandoffNotification = { threadId: string, incarnationId: string, realtimeSessionId: string | null, handoffId: string, itemId: string | null, source: ExternalRealtimeHandoffSource, inputTranscript: string, activeTranscript: Array<RealtimeTranscriptEntry>, transcriptTail: Array<RealtimeTranscriptEntry> | null, };
