// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RealtimeConversationVersion } from "../RealtimeConversationVersion";

/**
 * EXPERIMENTAL - emitted when thread realtime startup is accepted.
 */
export type ThreadRealtimeStartedNotification = {
/**
 * Present for external sessions; changes on every successful start.
 */
incarnationId: string | null, threadId: string, realtimeSessionId: string | null, version: RealtimeConversationVersion, };
