// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagePhase } from "./MessagePhase";

export type ExternalRealtimeEvent = { "type": "itemStarted", itemId: string, phase: MessagePhase | null, text: string | null, } | { "type": "itemDelta", itemId: string, delta: string, } | { "type": "itemEnded", itemId: string, text: string, phase: MessagePhase | null, } | { "type": "workSettled", handoffIds: Array<string>, } | { "type": "workFailed", message: string, handoffIds: Array<string>, } | { "type": "workCancelled", handoffIds: Array<string>, };
